# image will be published to ghcr.io/<user>/<name>
name: broccoli
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-base
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
                  
  - type: script
    snippets:
      - "sed -i '0,/enabled=0/s//enabled=1/' /etc/yum.repos.d/rpmfusion-nonfree.repo"
      - "sed -i '0,/enabled=0/s//enabled=1/' /etc/yum.repos.d/rpmfusion-nonfree-updates.repo"
      - "sed -i '0,/enabled=0/s//enabled=1/' /etc/yum.repos.d/rpmfusion-nonfree-updates-testing.repo"
    scripts:
      - enable-zerotier-repo.sh # I could have used rpm-ostree module to add the repo. But not sure how to make it accept the ZeroTier's GPG key.
      - fix-mediatek-bt.sh # kernel 6.9.1 broke firmware loading for that card

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/lukenukem/asus-linux/repo/fedora-%OS_VERSION%/lukenukem-asus-linux-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/sentry/switcheroo-control_discrete/repo/fedora-%OS_VERSION%/sentry-switcheroo-control_discrete-fedora-%OS_VERSION%.repo
    install:
      - akmod-nvidia 
      - xorg-x11-drv-nvidia-cuda 
      - xorg-x11-drv-nvidia-power 
      - asusctl
      - fish
      - fastfetch
      - supergfxctl
      - distrobox
      - zerotier-one
      - waydroid
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: script
    snippets:
      - "rpm-ostree kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1"
      
  - type: default-flatpaks
    notify: true
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.github.tchx84.Flatseal
        - com.google.Chrome
        - com.brave.Browser
        - com.valvesoftware.Steam
        - com.valvesoftware.Steam.CompatibilityTool.Proton-GE
        - com.usebottles.bottles
        - org.remmina.Remmina
        - com.visualstudio.code
        - com.bitwarden.desktop
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: systemd
    system:
      enabled:
        - nvidia-suspend.service
        - nvidia-resume.service
        - nvidia-hibernate.service
        - supergfxd.service
        - zerotier-one.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

